# Generated by Django 5.2.5 on 2026-01-19 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
    ]
