# Generated by Django 5.2.5 on 2025-08-30 18:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guideprofile',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='guideprofile',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='guide_images/'),
        ),
        migrations.AlterField(
            model_name='guideprofile',
            name='user',
            field=models.OneToOneField(limit_choices_to={'role': 'guide'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
