# Generated by Django 5.2.5 on 2025-08-30 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('difficulty', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('duration', models.CharField(max_length=50)),
                ('altitude', models.IntegerField()),
                ('best_season', models.CharField(max_length=50)),
                ('images', models.ImageField(upload_to='trek_images/')),
            ],
        ),
    ]
