# Generated by Django 5.2.5 on 2025-08-30 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trek',
            name='images',
        ),
        migrations.AddField(
            model_name='trek',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='trek_images/'),
        ),
        migrations.AlterField(
            model_name='trek',
            name='difficulty',
            field=models.CharField(choices=[('Easy', 'Easy'), ('Moderate', 'Moderate'), ('Hard', 'Hard')], max_length=10),
        ),
    ]
