# Generated by Django 5.2.5 on 2025-08-30 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0002_remove_trek_images_trek_image_alter_trek_difficulty'),
    ]

    operations = [
        migrations.AddField(
            model_name='trek',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
