# Generated by Django 5.2.5 on 2026-01-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treks', '0003_trek_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trek',
            name='image',
            field=models.CharField(blank=True, default='', max_length=500),
        ),
    ]
