# Generated by Django 5.2.5 on 2025-08-30 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_review'),
        ('guides', '0002_guideprofile_bio_guideprofile_profile_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='guide',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='guides.guideprofile'),
        ),
    ]
