# Generated by Django 5.2.5 on 2026-01-19 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_alter_booking_guide'),
        ('treks', '0004_alter_trek_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='trekker',
        ),
        migrations.AddField(
            model_name='booking',
            name='additional_comments',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='email',
            field=models.EmailField(default='noreply@trekmate.com', max_length=254),
        ),
        migrations.AddField(
            model_name='booking',
            name='hiking_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='name',
            field=models.CharField(default='Guest', max_length=200),
        ),
        migrations.AddField(
            model_name='booking',
            name='preferred_dates',
            field=models.TextField(default='', help_text="User's preferred dates or time period"),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_treks',
            field=models.TextField(default='', help_text='Comma-separated trek names'),
        ),
        migrations.AddField(
            model_name='booking',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trek',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='treks.trek'),
        ),
    ]
